import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export const metadata = {
  title: {
    default: 'Static Blog',
    template: '%s | Static Blog',
  },
  description: {
    default: 'Generated by The J-Man',
    template: '%s',
  }
}

// export const metadata: Metadata = {
//   title: {
//     default: 'Static Blog',
//     template: '%s | Static Blog',
//   },
//   description: {
//     default: 'Generated by The Jason',
//     template: '%s',
//   }
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Navbar/>
        <main className='pt-[112px]'>
        {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}
